language: android
android:
        components:
                - build-tools-24.0.1
                - android-15
                - extra-android-m2repository
script:
        - ./gradlew build
before_install:
        - chmod +x gradlew