language: android
android:
        components:
                - platform-tools
                - tools
                - build-tools-24.0.1
                - android-15
script:
        - ./gradlew build
before_install:
        - chmod +x gradlew